### PR TITLE
refactor of clothing menu

### PR DESCRIPTION
**Pull request by TrymTube**
I made it easier to add and configure clothing for the ambulancejob I think the job needed that since it hasnt been changed for years as far as I know

### CODE REVIEW

**Comment by Gellipapa** [comment]
@TrymTube Hi! Thank you good job.

**Review by Gellipapa — APPROVED** [review]

**Comment by TrymTube** [comment]
> @TrymTube Hi! Thank you good job.

Will this be merged into main?

**Comment by Gellipapa** [comment]
@TrymTube Hi! Yes, but we need to test it, and by the way, we also need to solve backwards compatibility for someone who still has their clothes stored in a database.

**Comment by TrymTube** [comment]
@Gellipapa Fantik has told me that you are going to handle the backwards compatibility

**Comment by Gellipapa** [comment]
> @Gellipapa Fantik has told me that the team is going to handle the backwards compatibility

Yes, that's true, but we're not merging, until that's done, it can't go into main.

**Pull request merged**
