### PR TITLE
esx_ambulancejob save isDied in metadata

### PR DESCRIPTION
**Pull request by Marvisak**
The resource uses is_dead field in DB, which is now kinda pointless because ESX can store metadata of players.

### CODE REVIEW

**Comment by Gellipapa** [comment]
@Marvisak Hi! Thank you for open pull request but we should do it backwards compatiblity.

**Comment by Gellipapa** [comment]
> @Gellipapa since when is ESX trying to be backwards compatible, you guys literally removed an event that destroyed compatibility with every single resource written before.

Hi! What do you mean? GetSharedObject?

**Comment by Marvisak** [comment]
Yes

**Comment by Gellipapa** [comment]
> Yes

I've written it a couple of times but I'll write it again, I didn't take it out, but it's not going back in because I'm not going to bullshit people, once I made the decision it's out now everyone has moved on and can live without it.

**Comment by Marvisak** [comment]
I am not mad that the event changed, I just don't understand why you don't want to merge my PR because of backwards compatibility when ESX has history of not caring about backwards compatibility at all. If you add new features and don't want to use them then why even add them in the first place.

**Comment by Gellipapa** [comment]
> I am not mad that the event changed, I just don't understand why you don't want to merge my PR because of backwards compatibility when ESX has history of not caring about backwards compatibility at all. If you add new features and don't want to use them then why even add them in the first place.

We pay attention to it, but it's not easy because if we don't pay attention to one detail, it's bad. It's not easy, believe me the goal is not to make the core unplayable, it's just easier for many people to say things like that than to help the community.

**Pull request closed without merging**
