### PR TITLE
refactor: correction of security flaws

### PR DESCRIPTION
**Pull request by MoskalykA**

### CODE REVIEW

**Comment by MoskalykA** [comment]
Hi @Gellipapa 
Sorry to mention you but I would need someone to review my pull request as well as someone to test my changes, I am unable to do so.

**Comment by Gellipapa** [comment]
@Thekuca @TheFantomas Did you manage to test it or what a status?

**Comment by Gellipapa** [comment]
@TheFantomas @Thekuca Can you guys test this PR?

**Comment by Gellipapa** [comment]
@TheFantomas @Thekuca Hi! Any status?

**Comment by Thekuca** [comment]
@TheFantomas when are you available for testing?

**Comment by Gellipapa** [comment]
@TheFantomas @Thekuca Hi! Any status?

**Pull request closed without merging**
